import Head from "next/head";
import Header from "../components/Header";
import Todo from "../components/Todo";
import Masonry from "react-masonry-css";

const breakpointColumnsObj = {
  default: 4,
  3000: 6,
  2000: 5,
  1200: 3,
  1000: 2,
  500: 1,
};

const todos = [
  {
    title: 'learn React',
    description: 'learning react js in coding , programming'
  }
]

export default function Home() {
  return (
    <>
      <Head>
        <title>Next-Sanity Todo App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Header />

        <Masonry
          className="flex justify-between gap-2 sm:w-full lg:w-[95%] lg:mx-auto px-3 py-4 rounded"
          breakpointCols={breakpointColumnsObj}
        >
          {todos.map((todo, index) => (
            <Todo key={index} {...todo} />
          ))}
        </Masonry>
      </div>
    </>
  );
}
