import { useEffect } from "react";
import { signInWithPopup } from "firebase/auth";
import { auth, provider } from "../firebase";
import {client} from '../client'
import {useRouter} from 'next/router';
import Head from 'next/head';


const login = () => {
      const router = useRouter();
      const handleLogin = () => {
         signInWithPopup(auth, provider).then((user) => {
           localStorage.setItem("user", JSON.stringify(user.user));
           const { displayName, uid, photoURL } = user.user;
           const doc = {
             _id: uid,
             _type: "user",
             userName: displayName,
             image: photoURL,
           };
           client.createIfNotExists(doc).then(() => {
             router.push("/", { replace: true });
           }).catch(e => console.log(e));
         });
      };
    return (
      <>
      <Head>
        <title>Next-Sanity Notes App | Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className='flex items-center justify-center w-full h-screen bg-gray-200'>
            <button
              type="button"
              className="bg-white flex p-3 text-gray-900 cursor-pointer rounded-2xl focus:ring-2 focus:ring-gray-100 focus:scale-125 transition outline-none"
              onClick={handleLogin}
            >
              Login with Google
            </button>
        </div>
        </>
    )
}

export default login
